package com.malyvoj3.csvwvalidator

import com.malyvoj3.csvwvalidator.config.ProcessorConfig
import com.malyvoj3.csvwvalidator.domain.ValidationStatus
import com.malyvoj3.csvwvalidator.processor.CsvwProcessor
import com.malyvoj3.csvwvalidator.processor.ProcessingSettings
import com.malyvoj3.csvwvalidator.processor.result.ProcessingResult
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.test.context.ContextConfiguration
import spock.lang.Specification
import spock.lang.Unroll

@ContextConfiguration(classes = [
        ProcessorConfig.class
])
class CsvwProcessorIT extends Specification {

    @Autowired
    private CsvwProcessor csvwProcessor

    @Unroll
    def "#name - CSVW implementation report"() {
        when: "Receive URL of tabular data and/or its metadata"
        ProcessingResult result
        ProcessingSettings settings = new ProcessingSettings()
        settings.setStrictMode(false)
        if (tabularUrl != null && metadataUrl != null) {
            result = csvwProcessor.processTabularData(settings, tabularUrl, metadataUrl)
        } else if (tabularUrl != null) {
            result = csvwProcessor.processTabularData(settings, tabularUrl)
        } else if (metadataUrl != null) {
            result = csvwProcessor.processMetadata(settings, metadataUrl)
        }
        then: "It is successfully validated"
        expectedResult == result.getValidationStatus()
        where:
        name                                                                                            | tabularUrl                                                   | metadataUrl                                                                                 | expectedResult
        "Test 001: Simple table"                                                                        | "http://www.w3.org/2013/csvw/tests/test001.csv"              | null                                                                                        | ValidationStatus.PASSED
        "Test 005: Identifier references"                                                               | "http://www.w3.org/2013/csvw/tests/test005.csv"              | null                                                                                        | ValidationStatus.PASSED
        "Test 006: No identifiers"                                                                      | "http://www.w3.org/2013/csvw/tests/test006.csv"              | null                                                                                        | ValidationStatus.PASSED
        "Test 007: Joined table with unique identifiers"                                                | "http://www.w3.org/2013/csvw/tests/test007.csv"              | null                                                                                        | ValidationStatus.PASSED
        "Test 008: Microsyntax - internal field separator"                                              | "http://www.w3.org/2013/csvw/tests/test008.csv"              | null                                                                                        | ValidationStatus.PASSED
        "Test 009: Microsyntax - formatted time"                                                        | "http://www.w3.org/2013/csvw/tests/test009.csv"              | null                                                                                        | ValidationStatus.PASSED
        "Test 010: Country-codes-and-names example"                                                     | "http://www.w3.org/2013/csvw/tests/test010.csv"              | null                                                                                        | ValidationStatus.PASSED
        "Test 011: tree-ops example with metadata"                                                      | "http://www.w3.org/2013/csvw/tests/test011/tree-ops.csv"     | null                                                                                        | ValidationStatus.PASSED
        "Test 012: tree-ops example with directory metadata"                                            | "http://www.w3.org/2013/csvw/tests/test012/tree-ops.csv"     | null                                                                                        | ValidationStatus.PASSED
        "Test 013: tree-ops example from user metadata"                                                 | "http://www.w3.org/2013/csvw/tests/test013/tree-ops.csv"     | "http://www.w3.org/2013/csvw/tests/test013-user-metadata.json"                              | ValidationStatus.PASSED
        "Test 014: tree-ops example with linked metadata"                                               | "http://www.w3.org/2013/csvw/tests/test014/tree-ops.csv"     | null                                                                                        | ValidationStatus.PASSED
        "Test 015: tree-ops example with user and directory metadata"                                   | "http://www.w3.org/2013/csvw/tests/test015/tree-ops.csv"     | "http://www.w3.org/2013/csvw/tests/test015/user-metadata.json"                              | ValidationStatus.PASSED
        "Test 016: tree-ops example with linked and directory metadata"                                 | "http://www.w3.org/2013/csvw/tests/test016/tree-ops.csv"     | null                                                                                        | ValidationStatus.PASSED
        "Test 017: tree-ops example with file and directory metadata"                                   | "http://www.w3.org/2013/csvw/tests/test017/tree-ops.csv"     | null                                                                                        | ValidationStatus.PASSED
        "Test 018: tree-ops example with user, file and directory metadata"                             | "http://www.w3.org/2013/csvw/tests/test018/tree-ops.csv"     | "http://www.w3.org/2013/csvw/tests/test018/user-metadata.json"                              | ValidationStatus.PASSED
        "Test 023: dialect: header=false"                                                               | "http://www.w3.org/2013/csvw/tests/tree-ops.csv"             | "https://w3c.github.io/csvw/tests/reports/index.html#test_67f964a94cd7b26f36b32ef111590152" | ValidationStatus.PASSED
        "Test 027: tree-ops minimal output"                                                             | "http://www.w3.org/2013/csvw/tests/tree-ops.csv"             | "http://www.w3.org/2013/csvw/tests/test027-user-metadata.json"                              | ValidationStatus.PASSED
        "Test 028: countries.csv example"                                                               | "http://www.w3.org/2013/csvw/tests/countries.csv"            | null                                                                                        | ValidationStatus.PASSED
        "Test 029: countries.csv minimal"                                                               | "http://www.w3.org/2013/csvw/tests/countries.csv"            | null                                                                                        | ValidationStatus.PASSED
        "Test 030: countries.json example"                                                              | null                                                         | "http://www.w3.org/2013/csvw/tests/countries.json"                                          | ValidationStatus.PASSED
        "Test 031: countries.json example minimal output"                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/countries.json"                                          | ValidationStatus.PASSED
        "Test 032: events-listing.csv example"                                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test032/csv-metadata.json"                               | ValidationStatus.PASSED
        "Test 033: events-listing.csv minimal output"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test033/csv-metadata.json"                               | ValidationStatus.PASSED
        "Test 034: roles example"                                                                       | null                                                         | "http://www.w3.org/2013/csvw/tests/test034/csv-metadata.json"                               | ValidationStatus.ERROR
        "Test 035: roles minimal"                                                                       | null                                                         | "http://www.w3.org/2013/csvw/tests/test035/csv-metadata.json"                               | ValidationStatus.ERROR
        "Test 036: tree-ops-ext example"                                                                | "http://www.w3.org/2013/csvw/tests/test036/tree-ops-ext.csv" | null                                                                                        | ValidationStatus.PASSED
        "Test 037: tree-ops-ext minimal"                                                                | "http://www.w3.org/2013/csvw/tests/test037/tree-ops-ext.csv" | null                                                                                        | ValidationStatus.PASSED
        "Test 038: inherited properties propagation"                                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test038-metadata.json"                                   | ValidationStatus.PASSED
        "Test 039: valid inherited properties"                                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test039-metadata.json"                                   | ValidationStatus.PASSED
        "Test 040: invalid null"                                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test040-metadata.json"                                   | ValidationStatus.WARNING
        "Test 041: invalid lang"                                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test041-metadata.json"                                   | ValidationStatus.WARNING
        "Test 042: invalid textDirection"                                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test042-metadata.json"                                   | ValidationStatus.WARNING
        "Test 043: invalid separator"                                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test043-metadata.json"                                   | ValidationStatus.WARNING
        "Test 044: invalid ordered"                                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test044-metadata.json"                                   | ValidationStatus.WARNING
        "Test 045: invalid default"                                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test045-metadata.json"                                   | ValidationStatus.WARNING
        "Test 046: invalid dataype"                                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test046-metadata.json"                                   | ValidationStatus.WARNING
        "Test 047: invalid aboutUrl"                                                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test047-metadata.json"                                   | ValidationStatus.WARNING
        "Test 048: invalid propertyUrl"                                                                 | null                                                         | "http://www.w3.org/2013/csvw/tests/test048-metadata.json"                                   | ValidationStatus.WARNING
        "Test 049: invalid valueUrl"                                                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test049-metadata.json"                                   | ValidationStatus.WARNING
        "Test 059: dialect: invalid commentPrefix"                                                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test059-metadata.json"                                   | ValidationStatus.WARNING
        "Test 060: dialect: invalid delimiter"                                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test060-metadata.json"                                   | ValidationStatus.WARNING
        "Test 061: dialect: invalid doubleQuote"                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test061-metadata.json"                                   | ValidationStatus.WARNING
        "Test 062: dialect: invalid encoding"                                                           | null                                                         | "http://www.w3.org/2013/csvw/tests/test062-metadata.json"                                   | ValidationStatus.WARNING
        "Test 063: dialect: invalid header"                                                             | null                                                         | "http://www.w3.org/2013/csvw/tests/test063-metadata.json"                                   | ValidationStatus.WARNING
        "Test 065: dialect: invalid headerRowCount"                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test065-metadata.json"                                   | ValidationStatus.WARNING
        "Test 066: dialect: invalid lineTerminators"                                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test066-metadata.json"                                   | ValidationStatus.WARNING
        "Test 067: dialect: invalid quoteChar"                                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test067-metadata.json"                                   | ValidationStatus.WARNING
        "Test 068: dialect: invalid skipBlankRows"                                                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test068-metadata.json"                                   | ValidationStatus.WARNING
        "Test 069: dialect: invalid skipColumns"                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test069-metadata.json"                                   | ValidationStatus.WARNING
        "Test 070: dialect: invalid skipInitialSpace"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test070-metadata.json"                                   | ValidationStatus.WARNING
        "Test 071: dialect: invalid skipRows"                                                           | null                                                         | "http://www.w3.org/2013/csvw/tests/test071-metadata.json"                                   | ValidationStatus.WARNING
        "Test 072: dialect: invalid trim"                                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test072-metadata.json"                                   | ValidationStatus.WARNING
        "Test 073: invalid @language"                                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test073-metadata.json"                                   | ValidationStatus.WARNING
        "Test 074: empty tables"                                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test074-metadata.json"                                   | ValidationStatus.ERROR
        "Test 075: invalid tableGroup tableDirection"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test075-metadata.json"                                   | ValidationStatus.WARNING
        "Test 076: invalid table tableDirection"                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test076-metadata.json"                                   | ValidationStatus.WARNING
        "Test 077: invalid tableGroup @id"                                                              | null                                                         | "http://www.w3.org/2013/csvw/tests/test077-metadata.json"                                   | ValidationStatus.ERROR
        "Test 078: invalid table @id"                                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test078-metadata.json"                                   | ValidationStatus.ERROR
        "Test 079: invalid schema @id"                                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test079-metadata.json"                                   | ValidationStatus.ERROR
        "Test 080: invalid column @id"                                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test080-metadata.json"                                   | ValidationStatus.ERROR
        "Test 081: invalid dialect @id"                                                                 | null                                                         | "http://www.w3.org/2013/csvw/tests/test081-metadata.json"                                   | ValidationStatus.ERROR
        "Test 082: invalid template @id"                                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test082-metadata.json"                                   | ValidationStatus.ERROR
        "Test 083: invalid tableGroup @type"                                                            | null                                                         | "http://www.w3.org/2013/csvw/tests/test083-metadata.json"                                   | ValidationStatus.ERROR
        "Test 084: invalid table @type"                                                                 | null                                                         | "http://www.w3.org/2013/csvw/tests/test084-metadata.json"                                   | ValidationStatus.ERROR
        "Test 085: invalid schema @type"                                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test085-metadata.json"                                   | ValidationStatus.ERROR
        "Test 086: invalid column @type"                                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test086-metadata.json"                                   | ValidationStatus.ERROR
        "Test 087: invalid dialect @type"                                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test087-metadata.json"                                   | ValidationStatus.ERROR
        "Test 088: invalid transformation @type"                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test088-metadata.json"                                   | ValidationStatus.ERROR
        "Test 089: missing tables in TableGroup"                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test089-metadata.json"                                   | ValidationStatus.ERROR
        "Test 090: missing url in Table"                                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test090-metadata.json"                                   | ValidationStatus.ERROR
        "Test 092: invalid JSON"                                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test092-metadata.json"                                   | ValidationStatus.ERROR
        "Test 093: undefined properties"                                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test093-metadata.json"                                   | ValidationStatus.WARNING
        "Test 094: inconsistent array values: tables"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test094-metadata.json"                                   | ValidationStatus.WARNING
        "Test 095: inconsistent array values: transformations"                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test095-metadata.json"                                   | ValidationStatus.WARNING
        "Test 096: inconsistent array values: columns"                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test096-metadata.json"                                   | ValidationStatus.WARNING
        "Test 097: inconsistent array values: foreignKeys"                                              | null                                                         | "http://www.w3.org/2013/csvw/tests/test097-metadata.json"                                   | ValidationStatus.WARNING
        "Test 098: inconsistent array values: tables"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test098-metadata.json"                                   | ValidationStatus.ERROR
        "Test 099: inconsistent array values: transformations"                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test099-metadata.json"                                   | ValidationStatus.WARNING
        "Test 100: inconsistent array values: columns"                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test100-metadata.json"                                   | ValidationStatus.ERROR
        "Test 101: inconsistent array values: foreignKeys"                                              | null                                                         | "http://www.w3.org/2013/csvw/tests/test101-metadata.json"                                   | ValidationStatus.WARNING
        "Test 102: inconsistent link values: @id"                                                       | null                                                         | "http://www.w3.org/2013/csvw/tests/test102-metadata.json"                                   | ValidationStatus.WARNING
        "Test 103: inconsistent link values: url"                                                       | null                                                         | "http://www.w3.org/2013/csvw/tests/test103-metadata.json"                                   | ValidationStatus.ERROR
        "Test 104: invalid columnReference"                                                             | null                                                         | "http://www.w3.org/2013/csvw/tests/test104-metadata.json"                                   | ValidationStatus.ERROR
        "Test 105: invalid primaryKey"                                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test105-metadata.json"                                   | ValidationStatus.WARNING
        "Test 106: invalid dialect"                                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test106-metadata.json"                                   | ValidationStatus.WARNING
        "Test 107: invalid tableSchema"                                                                 | null                                                         | "http://www.w3.org/2013/csvw/tests/test107-metadata.json"                                   | ValidationStatus.ERROR
        "Test 108: invalid reference"                                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test108-metadata.json"                                   | ValidationStatus.ERROR
        "Test 109: titles with invalid language"                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test109-metadata.json"                                   | ValidationStatus.ERROR
        "Test 110: titles with non-string values"                                                       | null                                                         | "http://www.w3.org/2013/csvw/tests/test110-metadata.json"                                   | ValidationStatus.WARNING
        "Test 111: titles with invalid value"                                                           | null                                                         | "http://www.w3.org/2013/csvw/tests/test111-metadata.json"                                   | ValidationStatus.ERROR
        "Test 112: titles with non-string array values"                                                 | null                                                         | "http://www.w3.org/2013/csvw/tests/test112-metadata.json"                                   | ValidationStatus.WARNING
        "Test 113: invalid suppressOutput"                                                              | null                                                         | "http://www.w3.org/2013/csvw/tests/test113-metadata.json"                                   | ValidationStatus.WARNING
        "Test 114: invalid name"                                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test114-metadata.json"                                   | ValidationStatus.WARNING
        "Test 115: invalid virtual"                                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test115-metadata.json"                                   | ValidationStatus.WARNING
        "Test 116: file-metadata with query component not found"                                        | "http://www.w3.org/2013/csvw/tests/test116.csv?query"        | null                                                                                        | ValidationStatus.PASSED
        "Test 117: file-metadata not referencing file"                                                  | "http://www.w3.org/2013/csvw/tests/test117.csv"              | null                                                                                        | ValidationStatus.WARNING
        "Test 118: directory-metadata with query component"                                             | "http://www.w3.org/2013/csvw/tests/test118/action.csv?query" | null                                                                                        | ValidationStatus.PASSED
        "Test 119: directory-metadata not referencing file"                                             | "http://www.w3.org/2013/csvw/tests/test119/action.csv"       | null                                                                                        | ValidationStatus.WARNING
        "Test 120: link-metadata not referencing file"                                                  | "http://www.w3.org/2013/csvw/tests/test120.csv"              | null                                                                                        | ValidationStatus.WARNING
        "Test 121: user-metadata not referencing file"                                                  | "http://www.w3.org/2013/csvw/tests/test121.csv"              | "http://www.w3.org/2013/csvw/tests/test121-user-metadata.json"                              | ValidationStatus.PASSED
        "Test 122: link-metadata not describing file uses file-metadata"                                | "http://www.w3.org/2013/csvw/tests/test122.csv"              | null                                                                                        | ValidationStatus.WARNING
        "Test 123: file-metadata not describing file uses directory-metadata"                           | "http://www.w3.org/2013/csvw/tests/test123/action.csv"       | null                                                                                        | ValidationStatus.WARNING
        "Test 124: metadata with columns not matching csv titles"                                       | "http://www.w3.org/2013/csvw/tests/tree-ops.csv"             | "http://www.w3.org/2013/csvw/tests/test124-user-metadata.json"                              | ValidationStatus.ERROR
        "Test 125: required column with empty cell"                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test125-metadata.json"                                   | ValidationStatus.ERROR
        "Test 126: required column with cell matching null"                                             | null                                                         | "http://www.w3.org/2013/csvw/tests/test126-metadata.json"                                   | ValidationStatus.ERROR
        "Test 127: incompatible table"                                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test127-metadata.json"                                   | ValidationStatus.ERROR
        "Test 128: duplicate column names"                                                              | null                                                         | "http://www.w3.org/2013/csvw/tests/test128-metadata.json"                                   | ValidationStatus.ERROR
        "Test 129: columnn name as integer"                                                             | null                                                         | "http://www.w3.org/2013/csvw/tests/test129-metadata.json"                                   | ValidationStatus.WARNING
        "Test 130: invalid column name"                                                                 | null                                                         | "http://www.w3.org/2013/csvw/tests/test130-metadata.json"                                   | ValidationStatus.WARNING
        "Test 131: invalid column name"                                                                 | null                                                         | "http://www.w3.org/2013/csvw/tests/test131-metadata.json"                                   | ValidationStatus.WARNING
        "Test 132: name annotation from title percent encoded"                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test132-metadata.json"                                   | ValidationStatus.PASSED
        "Test 133: virtual before non-virtual"                                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test133-metadata.json"                                   | ValidationStatus.ERROR
        "Test 134: context in common property"                                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test134-metadata.json"                                   | ValidationStatus.ERROR
        "Test 135: @list value"                                                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test135-metadata.json"                                   | ValidationStatus.ERROR
        "Test 136: @set value"                                                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test136-metadata.json"                                   | ValidationStatus.ERROR
        "Test 137: @type out of range (as datatype)"                                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test137-metadata.json"                                   | ValidationStatus.ERROR
        "Test 138: @type out of range (as node type)"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test138-metadata.json"                                   | ValidationStatus.ERROR
        "Test 139: @type out of range (as node type) - string"                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test139-metadata.json"                                   | ValidationStatus.ERROR
        "Test 140: @type out of range (as node type) - integer"                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test140-metadata.json"                                   | ValidationStatus.ERROR
        "Test 141: @id out of range (as node type) - bnode"                                             | null                                                         | "http://www.w3.org/2013/csvw/tests/test141-metadata.json"                                   | ValidationStatus.ERROR
        "Test 142: @value with @language and @type"                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test142-metadata.json"                                   | ValidationStatus.ERROR
        "Test 143: @value with extra properties"                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test143-metadata.json"                                   | ValidationStatus.ERROR
        "Test 144: @language outside of @value"                                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test144-metadata.json"                                   | ValidationStatus.ERROR
        "Test 145: @value with invalid @language"                                                       | null                                                         | "http://www.w3.org/2013/csvw/tests/test145-metadata.json"                                   | ValidationStatus.ERROR
        "Test 146: Invalid faux-keyword"                                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test146-metadata.json"                                   | ValidationStatus.ERROR
        "Test 147: title incompatible with title on case"                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test147-metadata.json"                                   | ValidationStatus.ERROR
        "Test 148: title incompatible with title on language"                                           | null                                                         | "http://www.w3.org/2013/csvw/tests/test148-metadata.json"                                   | ValidationStatus.ERROR
        "Test 149: title compatible with title on less specific language"                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test149-metadata.json"                                   | ValidationStatus.PASSED
        "Test 150: non-builtin datatype (datatype value)"                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test150-metadata.json"                                   | ValidationStatus.WARNING
        "Test 151: non-builtin datatype (base value)"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test151-metadata.json"                                   | ValidationStatus.WARNING
        "Test 152: string format (valid combinations)"                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test152-metadata.json"                                   | ValidationStatus.PASSED
        "Test 153: string format (bad format string)"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test153-metadata.json"                                   | ValidationStatus.WARNING
        "Test 154: string format (value not matching format)"                                           | null                                                         | "http://www.w3.org/2013/csvw/tests/test154-metadata.json"                                   | ValidationStatus.ERROR
        "Test 155: number format (valid combinations)"                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test155-metadata.json"                                   | ValidationStatus.PASSED
        "Test 156: number format (bad format string)"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test156-metadata.json"                                   | ValidationStatus.WARNING
        "Test 157: number format (value not matching format)"                                           | null                                                         | "http://www.w3.org/2013/csvw/tests/test157-metadata.json"                                   | ValidationStatus.ERROR
        "Test 158: number format (valid combinations)"                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test158-metadata.json"                                   | ValidationStatus.PASSED
        "Test 159: number format (bad pattern format string)"                                           | null                                                         | "http://www.w3.org/2013/csvw/tests/test159-metadata.json"                                   | ValidationStatus.WARNING
        "Test 160: number format (not matching values with pattern)"                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test160-metadata.json"                                   | ValidationStatus.ERROR
        "Test 161: number format (not matching values without pattern)"                                 | null                                                         | "http://www.w3.org/2013/csvw/tests/test161-metadata.json"                                   | ValidationStatus.ERROR
        "Test 162: numeric format (consecutive groupChar)"                                              | null                                                         | "http://www.w3.org/2013/csvw/tests/test162-metadata.json"                                   | ValidationStatus.ERROR
        "Test 163: integer datatype with decimalChar"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test163-metadata.json"                                   | ValidationStatus.ERROR
        "Test 164: decimal datatype with exponent"                                                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test164-metadata.json"                                   | ValidationStatus.ERROR
        "Test 165: decimal type with NaN"                                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test165-metadata.json"                                   | ValidationStatus.ERROR
        "Test 166: decimal type with INF"                                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test166-metadata.json"                                   | ValidationStatus.ERROR
        "Test 167: decimal type with -INF"                                                              | null                                                         | "http://www.w3.org/2013/csvw/tests/test167-metadata.json"                                   | ValidationStatus.ERROR
        "Test 168: decimal with implicit groupChar"                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test168-metadata.json"                                   | ValidationStatus.PASSED
        "Test 169: invalid decimal"                                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test169-metadata.json"                                   | ValidationStatus.ERROR
        "Test 170: decimal with percent"                                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test170-metadata.json"                                   | ValidationStatus.PASSED
        "Test 171: decimal with per-mille"                                                              | null                                                         | "http://www.w3.org/2013/csvw/tests/test171-metadata.json"                                   | ValidationStatus.PASSED
        "Test 172: invalid byte"                                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test172-metadata.json"                                   | ValidationStatus.ERROR
        "Test 173: invald unsignedLong"                                                                 | null                                                         | "http://www.w3.org/2013/csvw/tests/test173-metadata.json"                                   | ValidationStatus.ERROR
        "Test 174: invalid unsignedShort"                                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test174-metadata.json"                                   | ValidationStatus.ERROR
        "Test 175: invalid unsignedByte"                                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test175-metadata.json"                                   | ValidationStatus.ERROR
        "Test 176: invalid positiveInteger"                                                             | null                                                         | "http://www.w3.org/2013/csvw/tests/test176-metadata.json"                                   | ValidationStatus.ERROR
        "Test 177: invalid negativeInteger"                                                             | null                                                         | "http://www.w3.org/2013/csvw/tests/test177-metadata.json"                                   | ValidationStatus.ERROR
        "Test 178: invalid nonPositiveInteger"                                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test178-metadata.json"                                   | ValidationStatus.ERROR
        "Test 179: invalid nonNegativeInteger"                                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test179-metadata.json"                                   | ValidationStatus.ERROR
        "Test 180: invalid double"                                                                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test180-metadata.json"                                   | ValidationStatus.ERROR
        "Test 181: invalid number"                                                                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test181-metadata.json"                                   | ValidationStatus.ERROR
        "Test 182: invalid float"                                                                       | null                                                         | "http://www.w3.org/2013/csvw/tests/test182-metadata.json"                                   | ValidationStatus.ERROR
        "Test 183: boolean format (valid combinations)"                                                 | null                                                         | "http://www.w3.org/2013/csvw/tests/test183-metadata.json"                                   | ValidationStatus.PASSED
        "Test 184: boolean format (bad format string)"                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test184-metadata.json"                                   | ValidationStatus.WARNING
        "Test 185: boolean format (value not matching format)"                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test185-metadata.json"                                   | ValidationStatus.ERROR
        "Test 186: boolean format (not matching datatype)"                                              | null                                                         | "http://www.w3.org/2013/csvw/tests/test186-metadata.json"                                   | ValidationStatus.ERROR
        "Test 187: date format (valid native combinations)"                                             | null                                                         | "http://www.w3.org/2013/csvw/tests/test187-metadata.json"                                   | ValidationStatus.PASSED
        "Test 188: date format (valid date combinations with formats)"                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test188-metadata.json"                                   | ValidationStatus.PASSED
        "Test 189: date format (valid time combinations with formats)"                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test189-metadata.json"                                   | ValidationStatus.PASSED
        "Test 190: date format (valid dateTime combinations with formats)"                              | null                                                         | "http://www.w3.org/2013/csvw/tests/test190-metadata.json"                                   | ValidationStatus.PASSED
        "Test 191: date format (bad format string)"                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test191-metadata.json"                                   | ValidationStatus.ERROR
        "Test 192: date format (value not matching format)"                                             | null                                                         | "http://www.w3.org/2013/csvw/tests/test192-metadata.json"                                   | ValidationStatus.ERROR
        "Test 193: duration format (valid combinations)"                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test193-metadata.json"                                   | ValidationStatus.PASSED
        "Test 194: duration format (value not matching format)"                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test194-metadata.json"                                   | ValidationStatus.ERROR
        "Test 195: values with matching length"                                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test195-metadata.json"                                   | ValidationStatus.PASSED
        "Test 196: values with wrong length"                                                            | null                                                         | "http://www.w3.org/2013/csvw/tests/test196-metadata.json"                                   | ValidationStatus.ERROR
        "Test 197: values with wrong maxLength"                                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test197-metadata.json"                                   | ValidationStatus.ERROR
        "Test 198: values with wrong minLength"                                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test198-metadata.json"                                   | ValidationStatus.ERROR
        "Test 199: length < minLength"                                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test199-metadata.json"                                   | ValidationStatus.ERROR
        "Test 200: length > maxLength"                                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test200-metadata.json"                                   | ValidationStatus.ERROR
        "Test 201: length on date"                                                                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test201-metadata.json"                                   | ValidationStatus.ERROR
        "Test 202: float matching constraints"                                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test202-metadata.json"                                   | ValidationStatus.PASSED
        "Test 203: float value constraint not matching minimum"                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test203-metadata.json"                                   | ValidationStatus.ERROR
        "Test 204: float value constraint not matching maximum"                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test204-metadata.json"                                   | ValidationStatus.ERROR
        "Test 205: float value constraint not matching minInclusive"                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test205-metadata.json"                                   | ValidationStatus.ERROR
        "Test 206: float value constraint not matching minExclusive"                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test206-metadata.json"                                   | ValidationStatus.ERROR
        "Test 207: float value constraint not matching maxInclusive"                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test207-metadata.json"                                   | ValidationStatus.ERROR
        "Test 208: float value constraint not matching maxExclusive"                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test208-metadata.json"                                   | ValidationStatus.ERROR
        "Test 209: date matching constraints"                                                           | null                                                         | "http://www.w3.org/2013/csvw/tests/test209-metadata.json"                                   | ValidationStatus.PASSED
        "Test 210: date value constraint not matching minimum"                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test210-metadata.json"                                   | ValidationStatus.ERROR
        "Test 211: date value constraint not matching maximum"                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test211-metadata.json"                                   | ValidationStatus.ERROR
        "Test 212: date value constraint not matching minInclusive"                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test212-metadata.json"                                   | ValidationStatus.ERROR
        "Test 213: date value constraint not matching minExclusive"                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test213-metadata.json"                                   | ValidationStatus.ERROR
        "Test 214: date value constraint not matching maxInclusive"                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test214-metadata.json"                                   | ValidationStatus.ERROR
        "Test 215: date value constraint not matching maxExclusive"                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test215-metadata.json"                                   | ValidationStatus.ERROR
        "Test 216: minInclusive and minExclusive"                                                       | null                                                         | "http://www.w3.org/2013/csvw/tests/test216-metadata.json"                                   | ValidationStatus.ERROR
        "Test 217: maxInclusive and maxExclusive"                                                       | null                                                         | "http://www.w3.org/2013/csvw/tests/test217-metadata.json"                                   | ValidationStatus.ERROR
        "Test 218: maxInclusive < minInclusive"                                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test218-metadata.json"                                   | ValidationStatus.ERROR
        "Test 219: maxExclusive = minInclusive"                                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test219-metadata.json"                                   | ValidationStatus.ERROR
        "Test 220: maxExclusive < minExclusive"                                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test220-metadata.json"                                   | ValidationStatus.ERROR
        "Test 221: maxInclusive = minExclusive"                                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test221-metadata.json"                                   | ValidationStatus.ERROR
        "Test 222: string datatype with minimum"                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test222-metadata.json"                                   | ValidationStatus.ERROR
        "Test 223: string datatype with maxium"                                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test223-metadata.json"                                   | ValidationStatus.ERROR
        "Test 224: string datatype with minInclusive"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test224-metadata.json"                                   | ValidationStatus.ERROR
        "Test 225: string datatype with maxInclusive"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test225-metadata.json"                                   | ValidationStatus.ERROR
        "Test 226: string datatype with minExclusive"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test226-metadata.json"                                   | ValidationStatus.ERROR
        "Test 227: string datatype with maxExclusive"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test227-metadata.json"                                   | ValidationStatus.ERROR
        "Test 228: length with separator"                                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test228-metadata.json"                                   | ValidationStatus.PASSED
        "Test 229: matching minLength with separator"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test229-metadata.json"                                   | ValidationStatus.PASSED
        "Test 230: failing minLength with separator"                                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test230-metadata.json"                                   | ValidationStatus.ERROR
        "Test 231: single column primaryKey success"                                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test231-metadata.json"                                   | ValidationStatus.PASSED
        "Test 232: single column primaryKey violation"                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test232-metadata.json"                                   | ValidationStatus.ERROR
        "Test 233: multiple column primaryKey success"                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test233-metadata.json"                                   | ValidationStatus.PASSED
        "Test 234: multiple column primaryKey violation"                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test234-metadata.json"                                   | ValidationStatus.ERROR
        "Test 235: rowTitles on one column"                                                             | null                                                         | "http://www.w3.org/2013/csvw/tests/test235-metadata.json"                                   | ValidationStatus.PASSED
        "Test 236: rowTitles on multiple columns"                                                       | null                                                         | "http://www.w3.org/2013/csvw/tests/test236-metadata.json"                                   | ValidationStatus.PASSED
        "Test 237: rowTitles on one column (minimal)"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test237-metadata.json"                                   | ValidationStatus.PASSED
        "Test 238: datatype value an absolute URL"                                                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test238-metadata.json"                                   | ValidationStatus.WARNING
        "Test 242: datatype @id an absolute URL"                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test242-metadata.json"                                   | ValidationStatus.PASSED
        "Test 243: invalid datatype @id"                                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test243-metadata.json"                                   | ValidationStatus.ERROR
        "Test 244: invalid datatype @id"                                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test244-metadata.json"                                   | ValidationStatus.ERROR
        "Test 245: date format (valid time combinations with formats and milliseconds)"                 | null                                                         | "http://www.w3.org/2013/csvw/tests/test245-metadata.json"                                   | ValidationStatus.PASSED
        "Test 246: date format (valid dateTime combinations with formats and milliseconds)"             | null                                                         | "http://www.w3.org/2013/csvw/tests/test246-metadata.json"                                   | ValidationStatus.PASSED
        "Test 247: date format (extra milliseconds)"                                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test247-metadata.json"                                   | ValidationStatus.ERROR
        "Test 248: Unicode in non-Normalized form"                                                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test248-metadata.json"                                   | ValidationStatus.PASSED
        "Test 249: http normalization"                                                                  | "http://www.w3.org/2013/csvw/tests/test249.csv"              | "http://www.w3.org/2013/csvw/tests/test249-user-metadata.json"                              | ValidationStatus.PASSED
        "Test 250: valid case"                                                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test250-metadata.json"                                   | ValidationStatus.PASSED
        "Test 251: missing source reference"                                                            | null                                                         | "http://www.w3.org/2013/csvw/tests/test251-metadata.json"                                   | ValidationStatus.ERROR
        "Test 252: missing destination reference column"                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test252-metadata.json"                                   | ValidationStatus.ERROR
        "Test 253: missing destination table"                                                           | null                                                         | "http://www.w3.org/2013/csvw/tests/test253-metadata.json"                                   | ValidationStatus.ERROR
        "Test 254: foreign key single column same table"                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test254-metadata.json"                                   | ValidationStatus.PASSED
        "Test 255: foreign key single column different table"                                           | null                                                         | "http://www.w3.org/2013/csvw/tests/test255-metadata.json"                                   | ValidationStatus.PASSED
        "Test 256: foreign key multiple columns"                                                        | null                                                         | "http://www.w3.org/2013/csvw/tests/test256-metadata.json"                                   | ValidationStatus.PASSED
        "Test 257: foreign key no referenced row"                                                       | null                                                         | "http://www.w3.org/2013/csvw/tests/test257-metadata.json"                                   | ValidationStatus.ERROR
        "Test 258: foreign key multiple referenced rows"                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test258-metadata.json"                                   | ValidationStatus.ERROR
        "Test 259: tree-ops example with csvm.json (w3.org/.well-known/csvm)"                           | "http://www.w3.org/2013/csvw/tests/test259/tree-ops.csv"     | null                                                                                        | ValidationStatus.PASSED
        "Test 260: tree-ops example with {+url}.json (w3.org/.well-known/csvm)"                         | "http://www.w3.org/2013/csvw/tests/test260/tree-ops.csv"     | null                                                                                        | ValidationStatus.PASSED
        "Test 261: maxLength < minLength"                                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test261-metadata.json"                                   | ValidationStatus.ERROR
        "Test 263: @type on a common property can be a built-in type"                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test263-metadata.json"                                   | ValidationStatus.PASSED
        "Test 264: @type on a common property can be a CURIE if the prefix is one of the built-in ones" | null                                                         | "http://www.w3.org/2013/csvw/tests/test264-metadata.json"                                   | ValidationStatus.PASSED
        "Test 266: `null` contains an array of (valid) string & (invalid) numeric values"               | null                                                         | "http://www.w3.org/2013/csvw/tests/test266-metadata.json"                                   | ValidationStatus.WARNING
        "Test 267: @id on datatype is invalid (eg starts with _:)"                                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test267-metadata.json"                                   | ValidationStatus.ERROR
        "Test 268: `base` missing on datatype (defaults to string)"                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test268-metadata.json"                                   | ValidationStatus.PASSED
        "Test 269: `format` for a boolean datatype is a string but in the wrong form (eg YN)"           | null                                                         | "http://www.w3.org/2013/csvw/tests/test269-metadata.json"                                   | ValidationStatus.ERROR
        "Test 270: transformation includes an invalid property (eg foo)"                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test270-metadata.json"                                   | ValidationStatus.WARNING
        "Test 271: foreign key includes an invalid property (eg `dc:description`)"                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test271-metadata.json"                                   | ValidationStatus.ERROR
        "Test 272: foreign key reference includes an invalid property (eg `dc:description`)"            | null                                                         | "http://www.w3.org/2013/csvw/tests/test272-metadata.json"                                   | ValidationStatus.ERROR
        "Test 273: `@base` set in `@context` overriding eg CSV location"                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test273-metadata.json"                                   | ValidationStatus.PASSED
        "Test 274: `@context` object includes properties other than `@base` and `@language`"            | null                                                         | "http://www.w3.org/2013/csvw/tests/test274-metadata.json"                                   | ValidationStatus.ERROR
        "Test 275: property acceptable on column appears on table group"                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test275-metadata.json"                                   | ValidationStatus.WARNING
        "Test 276: property acceptable on column appears on table"                                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test276-metadata.json"                                   | ValidationStatus.WARNING
        "Test 277: property acceptable on table appears on column"                                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test277-metadata.json"                                   | ValidationStatus.WARNING
        "Test 278: CSV has more headers than there are columns in the metadata"                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test278-metadata.json"                                   | ValidationStatus.ERROR
        "Test 279: duration not matching xsd pattern"                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test279-metadata.json"                                   | ValidationStatus.ERROR
        "Test 280: dayTimeDuration not matching xsd pattern"                                            | null                                                         | "http://www.w3.org/2013/csvw/tests/test280-metadata.json"                                   | ValidationStatus.ERROR
        "Test 281: yearMonthDuration not matching xsd pattern"                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test281-metadata.json"                                   | ValidationStatus.ERROR
        "Test 282: valid number patterns"                                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test282-metadata.json"                                   | ValidationStatus.PASSED
        "Test 283: valid number patterns (signs and percent/permille)"                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test283-metadata.json"                                   | ValidationStatus.PASSED
        "Test 284: valid number patterns (grouping)"                                                    | null                                                         | "http://www.w3.org/2013/csvw/tests/test284-metadata.json"                                   | ValidationStatus.PASSED
        "Test 285: valid number patterns (fractional grouping)"                                         | null                                                         | "http://www.w3.org/2013/csvw/tests/test285-metadata.json"                                   | ValidationStatus.PASSED
        "Test 286: invalid ##0 1,234"                                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test286-metadata.json"                                   | ValidationStatus.ERROR
        "Test 287: invalid ##0 123.4"                                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test287-metadata.json"                                   | ValidationStatus.ERROR
        "Test 288: invalid #,#00 1"                                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test288-metadata.json"                                   | ValidationStatus.ERROR
        "Test 289: invalid #,#00 1234"                                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test289-metadata.json"                                   | ValidationStatus.ERROR
        "Test 290: invalid #,#00 12,34"                                                                 | null                                                         | "http://www.w3.org/2013/csvw/tests/test290-metadata.json"                                   | ValidationStatus.ERROR
        "Test 291: invalid #,#00 12,34,567"                                                             | null                                                         | "http://www.w3.org/2013/csvw/tests/test291-metadata.json"                                   | ValidationStatus.ERROR
        "Test 292: invalid #,##,#00 1"                                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test292-metadata.json"                                   | ValidationStatus.ERROR
        "Test 293: invalid #,##,#00 1234"                                                               | null                                                         | "http://www.w3.org/2013/csvw/tests/test293-metadata.json"                                   | ValidationStatus.ERROR
        "Test 294: invalid #,##,#00 12,34"                                                              | null                                                         | "http://www.w3.org/2013/csvw/tests/test294-metadata.json"                                   | ValidationStatus.ERROR
        "Test 295: invalid #,##,#00 1,234,567"                                                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test295-metadata.json"                                   | ValidationStatus.ERROR
        "Test 296: invalid #0.# 12.34"                                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test296-metadata.json"                                   | ValidationStatus.ERROR
        "Test 297: invalid #0.# 1,234.5"                                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test297-metadata.json"                                   | ValidationStatus.ERROR
        "Test 298: invalid #0.0 1"                                                                      | null                                                         | "http://www.w3.org/2013/csvw/tests/test298-metadata.json"                                   | ValidationStatus.ERROR
        "Test 299: invalid #0.0 12.34"                                                                  | null                                                         | "http://www.w3.org/2013/csvw/tests/test299-metadata.json"                                   | ValidationStatus.ERROR
        "Test 300: invalid #0.0# 1"                                                                     | null                                                         | "http://www.w3.org/2013/csvw/tests/test300-metadata.json"                                   | ValidationStatus.ERROR
        "Test 301: invalid #0.0# 12.345"                                                                | null                                                         | "http://www.w3.org/2013/csvw/tests/test301-metadata.json"                                   | ValidationStatus.ERROR
        "Test 302: invalid #0.0#,# 1"                                                                   | null                                                         | "http://www.w3.org/2013/csvw/tests/test302-metadata.json"                                   | ValidationStatus.ERROR
        "Test 303: invalid #0.0#,# 12.345"                                                              | null                                                         | "http://www.w3.org/2013/csvw/tests/test303-metadata.json"                                   | ValidationStatus.ERROR
        "Test 304: invalid #0.0#,# 12.34,567"                                                           | null                                                         | "http://www.w3.org/2013/csvw/tests/test304-metadata.json"                                   | ValidationStatus.ERROR
        "Test 305: multiple values with same subject and property (unordered)"                          | null                                                         | "http://www.w3.org/2013/csvw/tests/test305-metadata.json"                                   | ValidationStatus.PASSED
        "Test 306: multiple values with same subject and property (ordered)"                            | null                                                         | "http://www.w3.org/2013/csvw/tests/test306-metadata.json"                                   | ValidationStatus.PASSED
        "Test 307: multiple values with same subject and property (ordered and unordered)"              | null                                                         | "http://www.w3.org/2013/csvw/tests/test307-metadata.json"                                   | ValidationStatus.PASSED
    }

}
